I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 251, in script
    with Move(.5)
TypeError: Move() takes at least 3 arguments (1 given)

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 251, in script
    with Move(.5)
  File "C:\Users\Cedric\Documents\renpy-6.99.11-sdk\renpy\ast.py", line 1265, in execute
    renpy.exports.with_statement(trans, paired)
  File "C:\Users\Cedric\Documents\renpy-6.99.11-sdk\renpy\exports.py", line 1370, in with_statement
    return renpy.game.interface.do_with(trans, paired, clear=clear)
  File "C:\Users\Cedric\Documents\renpy-6.99.11-sdk\renpy\display\core.py", line 2058, in do_with
    clear=clear)
  File "C:\Users\Cedric\Documents\renpy-6.99.11-sdk\renpy\display\core.py", line 2496, in interact
    repeat, rv = self.interact_core(preloads=preloads, **kwargs)
  File "C:\Users\Cedric\Documents\renpy-6.99.11-sdk\renpy\display\core.py", line 2717, in interact_core
    new_widget=layers_root)
  File "C:\Users\Cedric\Documents\renpy-6.99.11-sdk\renpy\curry.py", line 38, in __call__
    **dict(self.kwargs.items() + kwargs.items()))
TypeError: Move() takes at least 3 arguments (1 given)

Windows-8-6.2.9200
Ren'Py 6.99.11.1749
Rutgers Love-iversity 1.0
